### ISSUE TITLE
Bump version on crates.io

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#108]
Could we have a checklist on bumping the version on crates.io ? Things that should be done before bumping...

@atroche

**Comment by atroche** [comment]
For sure. I think the first thing I'll do is put together a changelog. I'm guessing a bump to 0.2 is appropriate? I know that under semver you're supposed to do a major version bump with breaking API changes, but I'd rather wait until the crates in less flux before doing a 1.0 release.

What else do you think needs to be done before bumping?

**Comment by lukaslueg** [comment]
I'd suggest staying with 0.1, since there is still a lot of flex, docs are missing and so on. API breakage in `0.1` is to be expected.

**Comment by lukaslueg** [comment]
[Bumped](https://github.com/atroche/rust-headless-chrome/commits/v0.1.4)
