### ISSUE TITLE
Gitter channel for rust-headless-chrome discussion?

### ISSUE THREAD

**Issue by bee-git** [atroche/rust-headless-chrome#109]
I wonder if there is any interest in opening a Gitter channel for rust-headless-chrome. I have used the Gitter channel for Diesel on several occasions and found it very useful. Of course, the IRC channels also are great, but I wonder if a Gitter channel would be easier to get up and running.

(I know that the Actix Gitter channel also is very active and is a great resource for people who use that set of crates.)

I make this suggestion because I suspect I'm not the only one who has questions about using the crate that don't rise to the level of an "issue", yet discussing the questions might prove helpful to a number of people, not just myself.

**Comment by atroche** [comment]
@bee-git you're in luck, I just created a Discord server yesterday on the suggestion of someone who emailed me: https://discord.gg/yyGEzcc

cc @leshow @lukaslueg

**Comment by atroche** [comment]
oh, and the badge is in the readme now. Open to switching to Gitter if there are compelling reasons :)

**Comment by bee-git** [comment]
Glad to hear about the new Discord server. I've not used Discord before, so I can't compare it to Gitter. I like that I can use Gitter by just using an existing account, such as my Github account. I believe with Discord you have to create a completely new account. But I can do that if necessary. If you're more comfortable with Discord, that's fine (and also probably what's most important).

I appreciate your being open to suggestions on issues such as this.

**Comment by atroche** [comment]
Yeah, I think I'll stick with Discord for now, sorry for the bother!

**Comment by leshow** [comment]
Thanks for the heads up
