### ISSUE TITLE
Is there any plan to implement an async version?

### ISSUE THREAD

**Issue by jianglibo** [atroche/rust-headless-chrome#111]
I had been worked for a while. Can we discuss and learn each other?

**Comment by leshow** [comment]
see comment [here](https://github.com/atroche/rust-headless-chrome/issues/106#issuecomment-474605243)

**Comment by atroche** [comment]
See also this reddit comment: https://www.reddit.com/r/rust/comments/aqgsxk/announcing_the_headless_chrome_crate_puppeteer/eggd0e9/

**Comment by shirshak55** [comment]
@atroche Async await is great for multiple browser, tabs etc and should simply api too much right?

**Comment by atroche** [comment]
@shirshak55 I think it's debatable if the benefits are worth the costs -- for this crate but also for me personally ;)

FWIW I'm having no trouble running many browsers (like 30+) with many tabs at once. Basically, resource usage is so heavily dominated by Chrome itself that the overhead of having a thread per browser connection pales into insignificance.

Re the API, is there anything about it at the moment that doesn't feel simple? I'll try to find a way to fix that if so, it's still very WIP.

**Comment by shirshak55** [comment]
@atroche I mean there are some part where async simplify api alot like Promise racing where we wait for two selector and if any selector appears Promise will fulfill it . 

And I wished the api was almost same as puppeteer :)

I do agree threads are ok for this case as resource usage is dominated by chrome which takes probably more than 100+mb whereas thread only take like 8mb.

**Comment by leshow** [comment]
Async/await was designed to give asynchronous code a similar API to
synchronous code. rust-headless-chrome is already synchronous, so
async/await isn't going to simplify anything for us in terms of API design.

Async/await is great, and I use it in some of my own projects, but I don't
think this crate necessarily needs it. Just my 2cents.
