### ISSUE TITLE
more good example

### ISSUE THREAD

**Issue by blue-bird1** [atroche/rust-headless-chrome#125]
`query_wikipedia.rs` use failure module, But not doc point this out.. For newbies, the example failure can be very frustrating

**Comment by lukaslueg** [comment]
Could you elaborate on what you mean by "use failure module, but no doc point this out" ?

**Comment by blue-bird1** [comment]
I add `headless_chrome = "0.1.4"` to cargo.toml.. Copy example code to main.rs.. Get a error `failed to resolve: use of undeclared type or module `failure``

**Comment by devmanny** [comment]
I added `failure = "0.1.5"` to cargo [dependencies] file
