### ISSUE TITLE
Chrome should be launched with appropriate flags (like Puppeteer)

### ISSUE THREAD

**Issue by sdimkov** [atroche/rust-headless-chrome#127]
Puppeteer wisely disables much of the additional functionality in chrome that may intervene with the automation task at hand. On the opposite end, this crate starts Chrome with default settings. 

This issue is not so obvious when the tool downloads a clean chrome instance as it barely has any extra plugins or other functionality enabled. But when we try to run with our system chrome, things get ugly as various extensions, themes, usability settings and others start affecting the execution.

My suggestion is to implement the same flags as Puppeteer and add some launch option to add/remove/replace the list of flags.

[Here](https://github.com/GoogleChrome/puppeteer/blob/6860d73212d2a36fd789a9244667be574f396164/lib/Launcher.js#L38-L63) is a list of the 24 arguments Puppeteer passes to Google Chrome by default.

**Comment by sdimkov** [comment]
P.s. I'm willing to contribute a PR if the maintainers agree with my suggestion

**Comment by lukaslueg** [comment]
FWIW I'd appreciate stable defaults like the ones posted above if documented well.

**Comment by sdimkov** [comment]
Cool, I'll prepare a PR.

**Comment by atroche** [comment]
Thanks, that's a good idea. And it's definitely worth documenting which ones are on by default.
