### ISSUE TITLE
Remove traits that violate 'bare-trait-object'

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#131]
We currently allow [bare-trait-object](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#bare-trait-object), we should fix the offending lines and 'deny' `bare-trait-object` again.

**Comment by sdimkov** [comment]
Related commit: https://github.com/atroche/rust-headless-chrome/pull/130/commits/55381beac51c3dd541ce9a9af32af1cd6161365c

**Comment by atroche** [comment]
Fixed: https://github.com/atroche/rust-headless-chrome/commit/d837d61e935576044e75bc254ea0874dfaf1688c
