### ISSUE TITLE
Inspect response contents

### ISSUE THREAD

**Issue by theduke** [atroche/rust-headless-chrome#132]
Puppeteer allows to inspect the content of responses pretty easily. 

This is currently not possible with this crate, as far as I can tell?

(Specifically, I need to read the JSON body of api responses)

**Comment by theduke** [comment]
After checking the protocol, this would work by:

* Listening to the `Network.responseReceived` event and persisting the responses. 
* Exposing the buffered responses
* Providing a method to fetch the response body (`Network.getResponseBody`)

**Comment by atroche** [comment]
Are these methods useful to you? https://github.com/atroche/rust-headless-chrome/pull/98/files#diff-10542f9964382c1bc5ed6be77b44bbc4R558

**Comment by atroche** [comment]
Paired with this: https://github.com/atroche/rust-headless-chrome/pull/98/files#diff-c26f33b661dff38214feca636a345232R188
