### ISSUE TITLE
Use traits for Tab.request_interceptor and Tab.response_handler

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#137]
Right now they're boxed closures: https://github.com/atroche/myws/blob/8b1c24918fcbe6a1f551b90bbd3ed5ecc6f48e44/src/browser/tab/mod.rs#L36

See https://github.com/atroche/rust-headless-chrome/pull/133#discussion_r298800045

**Comment by mdrokz** [comment]
closing because of #195
