### ISSUE TITLE
LaunchOptionsBuilder

### ISSUE THREAD

**Issue by jeprojects** [atroche/rust-headless-chrome#139]
Does LaunchOptionsBuilder exist? In your examples you are using it but the crate 0.3 doesn't have it. Anything I am doing wrong?

Also this doesn't exist.
https://docs.rs/headless_chrome/0.3.0/headless_chrome/struct.LaunchOptions.html

**Comment by atroche** [comment]
Hi, I'm at on my phone at the moment so can't respond fully, but Launch OptionsBuilder is derived via https://docs.rs/derive_builder/0.7.2/derive_builder/. Are you getting compiler errors when you import it?

In any case, I clearly need to improve the docs.

**Comment by jeprojects** [comment]
@atroche Your right, it is generated :P All is working.
