### ISSUE TITLE
Proxies & Useragent

### ISSUE THREAD

**Issue by jeprojects** [atroche/rust-headless-chrome#140]
Is it possible to launch chromium using a proxy and custom useragent?

**Comment by atroche** [comment]
Not yet! We should probably add an option for passing arbitrary command line options to the Chrome binary so things like this can be supported more easily.

**Comment by jeprojects** [comment]
Any suggestion on naming for the extra command line options for LaunchOptions ?

**Comment by atroche** [comment]
No strong feelings :)

**Comment by Grav3y** [comment]
Do we know the status on this? Will proxies and custom UA's be coming soon?

**Comment by jeprojects** [comment]
@Grav3y https://github.com/atroche/rust-headless-chrome/pull/195

**Comment by chovy** [comment]
is this working yet? i'm thinking of switching to rust for my web scrapers but I need `--proxy` support and `--user-agent` support.

**Comment by mdrokz** [comment]
Closing because of #195
