### ISSUE TITLE
Replace Network interception method calls with Fetch counterparts

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#144]
Fetch was [released near the end of October 2018](https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md#roll-protocol-to-r604358). Puppeteer is now [using it](https://github.com/GoogleChrome/puppeteer/blob/6860d73212d2a36fd789a9244667be574f396164/lib/NetworkManager.js#L145) in favour of `Network.setRequestInterception` etc.

Possibly related problem:
https://github.com/atroche/rust-headless-chrome/pull/141#issuecomment-516273796

**Comment by jeprojects** [comment]
https://github.com/atroche/rust-headless-chrome/pull/195

**Comment by mdrokz** [comment]
closing because of #195
