### ISSUE TITLE
NodeId wrong size

### ISSUE THREAD

**Issue by Erk-** [atroche/rust-headless-chrome#149]
I had problems with deserialising NodeId as it was larger than u16. It seems that in the protocol it is a javascript number so a f64 I would say that maybe changee it to either u32 or u64 to not exhaust the id fast.

**Comment by atroche** [comment]
Oh, interesting. I've had problems before where I sent across a `u32` when the protocol docs asked for `Number`, and Chrome sent back an error saying it was too large.

Maybe they've changed that, or maybe some things that are declared as `Number` are different from each other.

In any case, have upped NodeId to `u32` in https://github.com/atroche/rust-headless-chrome/commit/a7feb05238d91b6f0c25cd9c75e5df9c7d6f1cf9.

Thanks for the heads up!
