### ISSUE TITLE
How to keep connection alive for a long time?

### ISSUE THREAD

**Issue by ibaryshnikov** [atroche/rust-headless-chrome#151]
I have a use case where browser does a long calculation, 5 to 10 minutes. At the moment I'm getting an error `ConnectionClosed` after several minutes. Is there a way to extend timeouts? May be a flag for chrome itself? Because I tried cloning repo locally and changing all the timeouts to more than 10 minutes, and error still occurs.

**Comment by lukaslueg** [comment]
Are you blocking on an API call the entire time or idle-waiting? You could send a period keep-alive `.wait_for_element("body")` or something.

**Comment by ibaryshnikov** [comment]
@lukaslueg no, just idle. Thanks for the idea, I'll try this. Can I do such calls from another thread?

**Comment by lukaslueg** [comment]
Should work, if it compiles :-)

How do you know the computation is done if you're just idle-waiting? Can't you detect the ready-condition and periodically check on that?

**Comment by ibaryshnikov** [comment]
I didn't get what `idle` was for ) I'm doing `let result = call_js_fn("some async function"`

**Comment by atroche** [comment]
I'm going to try to get rid of the idle timeout altogether, it's not necessary and obviously clashing with real use cases. Thanks for the report.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ibaryshnikov** [comment]
I guess I figured out how to fix this. Closing in favor of #179
