### ISSUE TITLE
enable_response_handling get body

### ISSUE THREAD

**Issue by tingfeng-key** [atroche/rust-headless-chrome#153]
Hello, I am planning to use this library to get the response of the browser request, but in the use of enable_response_handling to get the body can not be done, I looked at the simple.rs in the test directory, get the body test is commented, according to the code of the comment can not  Running, how should I get the body of enable_response_handling?  Thank you

**Comment by atroche** [comment]
Currently it's not implemented correctly. I'm planning a rework of the networking functionality to better match Puppeteer's API / implementation soon.

**Comment by atroche** [comment]
Hi, I've updated the test and docstring for response handling in this PR:
https://github.com/atroche/rust-headless-chrome/pull/158

You should be fine getting the response body like the test does, as long as you wait a little bit to make sure the download has finished (unfortunately right now in this crate you can't find out exactly when the response body has finished downloading).

Please let me know if you run into problems.
