### ISSUE TITLE
how to get the cookie when login in the website

### ISSUE THREAD

**Issue by litttley** [atroche/rust-headless-chrome#156]
How to get the cookies after I log in is like  `await page.cookies()`  in puppeter

**Comment by atroche** [comment]
Yeah, sorry mate, no support at the moment. I really need to document that: https://github.com/atroche/rust-headless-chrome/issues/157

**Comment by atroche** [comment]
@litttley released in v0.7.0

**Comment by litttley** [comment]
thanks  I've got cookies.

**Comment by litttley** [comment]
thanks I've got the  cookies.
