### ISSUE TITLE
Choice of chromium install path

### ISSUE THREAD

**Issue by zbidwell** [atroche/rust-headless-chrome#175]
I would like to have the option to install chromium to an arbitrary path, instead of the default ProjectDirs location. Maybe as a setting in LaunchOptions (installing to the `path` option location if chrome wasn't found there might work).

If you are open to pull requests I might take a crack at it myself, but I would like to hear your thoughts on the interface for it

**Comment by atroche** [comment]
Hello! Thanks for asking.

Does overriding XDG_DATA_DIR satisfy your use case? If not, fair enough.

I think if we reuse path it may lead to situations where people are accidentally run the fetcher when they actually got the path to their installation wrong.

How about another field on LaunchOptions that specifies where to download to (and also to look for Chrome binaries in addition to the default search directories).

**Comment by lukaslueg** [comment]
Maybe pooling the "pull chromium"-functionality should be outsourced to an extra crate, shared with puppeteer?!

**Comment by zbidwell** [comment]
I'm not sure it would be worth the maintenance overhead of pulling into a separate crate. Puppeteer's browser fetching code is very similar to this already (Unless there is a puppeteer project using rust that I haven't heard of?).

On a side note, in puppeteer they install chrome either to a project-local folder or to an `options.path`. They also separate the fetching options from the launch options, which seems like it would be a good idea here.

https://github.com/GoogleChrome/puppeteer/blob/dc57d03c1957cc9fb44b4b8eebdefe26a39aeb20/lib/BrowserFetcher.js#L85

**Comment by atroche** [comment]
@lukaslueg maybe one day ;) for the moment I'm happy to support the fetcher as a non-default feature.
