### ISSUE TITLE
Make method call timeout configurable

### ISSUE THREAD

**Issue by ibaryshnikov** [atroche/rust-headless-chrome#179]
At the moment the timeout is hardcoded as 15 seconds
https://github.com/atroche/rust-headless-chrome/blob/master/src/browser/transport/mod.rs#L169

What about making it configurable? I run long computations in browser, and usually hit this error.

**Comment by atroche** [comment]
I'm definitely into this!

**Comment by atroche** [comment]
And also into bumping the default timeout as well...

**Comment by mdrokz** [comment]
fixed with #145
