### ISSUE TITLE
Ignore SSL Errors

### ISSUE THREAD

**Issue by P3GLEG** [atroche/rust-headless-chrome#184]
I was reading through the process.rs and wasn't able to find a way to add command line arguments. Probably for security reasons which I approve of. Is there any way you can add a field for `--ignore-certificate-errors`? I am doing some testing and require this flag in order to do local network testing not just localhost.

**Comment by jeprojects** [comment]
@P3GLEG Added it so you can add any command line options to the args method of LaunchOptionsBuilder::default().

https://github.com/atroche/rust-headless-chrome/pull/195

**Comment by P3GLEG** [comment]
Thanks man!
