### ISSUE TITLE
Easy way to search within descendants of an element

### ISSUE THREAD

**Issue by alexpdp7** [atroche/rust-headless-chrome#186]
Hi,

I'm trying to write a web scraper using this library, and along with https://github.com/atroche/rust-headless-chrome/issues/73 , it would be very useful to be able to run `find_element(s)` on an `Element`, so I could say `find_elements("tr")` then do `find_element(x)` to find specific columns of the table.

**Comment by mdrokz** [comment]
closing this because of #190
