### ISSUE TITLE
Add more of the protocol's Node type's fields to our corresponding struct

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#19]
There are 28 fields listed here: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-Node

We currently only deserialize 7:

https://github.com/atroche/rust-headless-chrome/blob/dcc5249cf6c890750a901c24b4e2527880b0b1d1/src/cdtp/dom.rs#L9-L18

**Comment by leshow** [comment]
I'm happy to take this issue and the one for deserializing as a HashMap instead of Vec. What should the Map be keyed on? the NodeId?

**Comment by atroche** [comment]
So the `attributes` field is listed as an array of strings representing a map, so `HashMap<String, String>` seems like a good first pass, although we could type alias those strings (or something like https://github.com/atroche/rust-headless-chrome/pull/7#discussion_r257049091 for the attribute name / values).

And, thanks! Yell if you need a hand.

**Comment by lukaslueg** [comment]
Please, lets keep this type-safe and not use a `HashMap`. If the protocol changes and fields come and go, we can always have serde handle optional fields. At some point all the `pub` fields may have to move behind accessors and maybe even `InternalNode`. Having a HashMap here feels like writing Python in Rust.

**Comment by atroche** [comment]
@lukaslueg I think you might have thought I was suggesting that the entire `Node` be represented as  a HashMap, but I was only proposing it for this field in the `Node` struct:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/29839/52928449-cdf36400-3393-11e9-8fc0-6b6e924427ed.png">

Given the format specified in the docs, it seems like a type safe thing to do.

**Comment by atroche** [comment]
(oh, and here's where I proposed it! just realised this issue was never explicitly reference in the above conversation: https://github.com/atroche/rust-headless-chrome/issues/18)
