### ISSUE TITLE
Could not auto detect a chrome executable

### ISSUE THREAD

**Issue by juzi5201314** [atroche/rust-headless-chrome#192]
I get an error on target: i686-pc-windows-msvc:

0009:fixme:thread:SetThreadStackGuarantee (0x32fe04): stub
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 14
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf e
0009:fixme:dbghelp_msc:dump 00000000: 06 00 0e 00 00 00 f2 f1                          ........        
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 24
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::traits::iterator::Iterator::all::check::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 4
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 4
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 14
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::traits::iterator::Iterator::all::check::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::traits::iterator::Iterator::all::check::closure-0 from 0 to 8
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for rand::rngs::entropy::EntropyRng from 0 to 16
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::map_fold::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::traits::iterator::Iterator::all::check::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::adapters::clone_try_fold::closure-0 from 0 to 12
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_symt:symt_set_udt_size Changing size for core::iter::traits::iterator::Iterator::all::check::closure-0 from 0 to 4
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 414
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 14
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 14
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 14
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 3e 00 1d 15 84 93 01 00 00 00 00 00 00 00 00 00  >...............
0009:fixme:dbghelp_msc:dump 00000010: 2c 00 00 00 3f 3f 5f 37 74 79 70 65 5f 69 6e 66  ,...??_7type_inf
0009:fixme:dbghelp_msc:dump 00000020: 6f 40 40 36 42 40 00 3f 3f 5f 45 74 79 70 65 5f  o@@6B@.??_Etype_
0009:fixme:dbghelp_msc:dump 00000030: 69 6e 66 6f 40 40 55 41 45 50 41 58 49 40 5a 00  info@@UAEPAXI@Z.
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 66 00 1d 15 1a 93 01 00 00 00 00 00 00 00 00 00  f...............
0009:fixme:dbghelp_msc:dump 00000010: 52 00 00 00 3f 3f 5f 37 65 78 63 65 70 74 69 6f  R...??_7exceptio
0009:fixme:dbghelp_msc:dump 00000020: 6e 40 73 74 64 40 40 36 42 40 00 3f 3f 5f 45 65  n@std@@6B@.??_Ee
0009:fixme:dbghelp_msc:dump 00000030: 78 63 65 70 74 69 6f 6e 40 73 74 64 40 40 55 41  xception@std@@UA
0009:fixme:dbghelp_msc:dump 00000040: 45 50 41 58 49 40 5a 00 3f 77 68 61 74 40 65 78  EPAXI@Z.?what@ex
0009:fixme:dbghelp_msc:dump 00000050: 63 65 70 74 69 6f 6e 40 73 74 64 40 40 55 42 45  ception@std@@UBE
0009:fixme:dbghelp_msc:dump 00000060: 50 42 44 58 5a 00 f2 f1                          PBDXZ...        
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 6e 00 1d 15 45 93 01 00 2e 94 01 00 00 00 00 00  n...E...........
0009:fixme:dbghelp_msc:dump 00000010: 5a 00 00 00 3f 3f 5f 37 62 61 64 5f 65 78 63 65  Z...??_7bad_exce
0009:fixme:dbghelp_msc:dump 00000020: 70 74 69 6f 6e 40 73 74 64 40 40 36 42 40 00 3f  ption@std@@6B@.?
0009:fixme:dbghelp_msc:dump 00000030: 3f 5f 45 62 61 64 5f 65 78 63 65 70 74 69 6f 6e  ?_Ebad_exception
0009:fixme:dbghelp_msc:dump 00000040: 40 73 74 64 40 40 55 41 45 50 41 58 49 40 5a 00  @std@@UAEPAXI@Z.
0009:fixme:dbghelp_msc:dump 00000050: 3f 77 68 61 74 40 65 78 63 65 70 74 69 6f 6e 40  ?what@exception@
0009:fixme:dbghelp_msc:dump 00000060: 73 74 64 40 40 55 42 45 50 42 44 58 5a 00 f2 f1  std@@UBEPBDXZ...
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 66 00 1d 15 5a 93 01 00 2e 94 01 00 00 00 00 00  f...Z...........
0009:fixme:dbghelp_msc:dump 00000010: 52 00 00 00 3f 3f 5f 37 62 61 64 5f 61 6c 6c 6f  R...??_7bad_allo
0009:fixme:dbghelp_msc:dump 00000020: 63 40 73 74 64 40 40 36 42 40 00 3f 3f 5f 45 62  c@std@@6B@.??_Eb
0009:fixme:dbghelp_msc:dump 00000030: 61 64 5f 61 6c 6c 6f 63 40 73 74 64 40 40 55 41  ad_alloc@std@@UA
0009:fixme:dbghelp_msc:dump 00000040: 45 50 41 58 49 40 5a 00 3f 77 68 61 74 40 65 78  EPAXI@Z.?what@ex
0009:fixme:dbghelp_msc:dump 00000050: 63 65 70 74 69 6f 6e 40 73 74 64 40 40 55 42 45  ception@std@@UBE
0009:fixme:dbghelp_msc:dump 00000060: 50 42 44 58 5a 00 f2 f1                          PBDXZ...        
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 7a 00 1d 15 6f 93 01 00 30 94 01 00 00 00 00 00  z...o...0.......
0009:fixme:dbghelp_msc:dump 00000010: 68 00 00 00 3f 3f 5f 37 62 61 64 5f 61 72 72 61  h...??_7bad_arra
0009:fixme:dbghelp_msc:dump 00000020: 79 5f 6e 65 77 5f 6c 65 6e 67 74 68 40 73 74 64  y_new_length@std
0009:fixme:dbghelp_msc:dump 00000030: 40 40 36 42 40 00 3f 3f 5f 45 62 61 64 5f 61 72  @@6B@.??_Ebad_ar
0009:fixme:dbghelp_msc:dump 00000040: 72 61 79 5f 6e 65 77 5f 6c 65 6e 67 74 68 40 73  ray_new_length@s
0009:fixme:dbghelp_msc:dump 00000050: 74 64 40 40 55 41 45 50 41 58 49 40 5a 00 3f 77  td@@UAEPAXI@Z.?w
0009:fixme:dbghelp_msc:dump 00000060: 68 61 74 40 65 78 63 65 70 74 69 6f 6e 40 73 74  hat@exception@st
0009:fixme:dbghelp_msc:dump 00000070: 64 40 40 55 42 45 50 42 44 58 5a 00              d@@UBEPBDXZ.    
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 62 00 1d 15 b7 93 01 00 2e 94 01 00 00 00 00 00  b...............
0009:fixme:dbghelp_msc:dump 00000010: 50 00 00 00 3f 3f 5f 37 62 61 64 5f 63 61 73 74  P...??_7bad_cast
0009:fixme:dbghelp_msc:dump 00000020: 40 73 74 64 40 40 36 42 40 00 3f 3f 5f 45 62 61  @std@@6B@.??_Eba
0009:fixme:dbghelp_msc:dump 00000030: 64 5f 63 61 73 74 40 73 74 64 40 40 55 41 45 50  d_cast@std@@UAEP
0009:fixme:dbghelp_msc:dump 00000040: 41 58 49 40 5a 00 3f 77 68 61 74 40 65 78 63 65  AXI@Z.?what@exce
0009:fixme:dbghelp_msc:dump 00000050: 70 74 69 6f 6e 40 73 74 64 40 40 55 42 45 50 42  ption@std@@UBEPB
0009:fixme:dbghelp_msc:dump 00000060: 44 58 5a 00                                      DXZ.            
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 66 00 1d 15 cf 93 01 00 2e 94 01 00 00 00 00 00  f...............
0009:fixme:dbghelp_msc:dump 00000010: 54 00 00 00 3f 3f 5f 37 62 61 64 5f 74 79 70 65  T...??_7bad_type
0009:fixme:dbghelp_msc:dump 00000020: 69 64 40 73 74 64 40 40 36 42 40 00 3f 3f 5f 45  id@std@@6B@.??_E
0009:fixme:dbghelp_msc:dump 00000030: 62 61 64 5f 74 79 70 65 69 64 40 73 74 64 40 40  bad_typeid@std@@
0009:fixme:dbghelp_msc:dump 00000040: 55 41 45 50 41 58 49 40 5a 00 3f 77 68 61 74 40  UAEPAXI@Z.?what@
0009:fixme:dbghelp_msc:dump 00000050: 65 78 63 65 70 74 69 6f 6e 40 73 74 64 40 40 55  exception@std@@U
0009:fixme:dbghelp_msc:dump 00000060: 42 45 50 42 44 58 5a 00                          BEPBDXZ.        
0009:fixme:dbghelp_msc:codeview_parse_one_type Unsupported type-id leaf 151d
0009:fixme:dbghelp_msc:dump 00000000: 76 00 1d 15 e7 93 01 00 33 94 01 00 00 00 00 00  v.......3.......
0009:fixme:dbghelp_msc:dump 00000010: 62 00 00 00 3f 3f 5f 37 5f 5f 6e 6f 6e 5f 72 74  b...??_7__non_rt
0009:fixme:dbghelp_msc:dump 00000020: 74 69 5f 6f 62 6a 65 63 74 40 73 74 64 40 40 36  ti_object@std@@6
0009:fixme:dbghelp_msc:dump 00000030: 42 40 00 3f 3f 5f 45 5f 5f 6e 6f 6e 5f 72 74 74  B@.??_E__non_rtt
0009:fixme:dbghelp_msc:dump 00000040: 69 5f 6f 62 6a 65 63 74 40 73 74 64 40 40 55 41  i_object@std@@UA
0009:fixme:dbghelp_msc:dump 00000050: 45 50 41 58 49 40 5a 00 3f 77 68 61 74 40 65 78  EPAXI@Z.?what@ex
0009:fixme:dbghelp_msc:dump 00000060: 63 65 70 74 69 6f 6e 40 73 74 64 40 40 55 42 45  ception@std@@UBE
0009:fixme:dbghelp_msc:dump 00000070: 50 42 44 58 5a 00 f2 f1                          PBDXZ...        
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 24
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 424
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_fetch_type Cannot locate type 400
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0a 00 68 11 01 00 00 00 3c ed 00 00              ..h.....<...    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 1a 00 68 11 05 00 00 00 b4 f2 00 00 b5 f2 00 00  ..h.............
0009:fixme:dbghelp_msc:dump 00000010: e0 f2 00 00 e2 f2 00 00 e3 f2 00 00              ............    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0a 00 68 11 01 00 00 00 e4 f2 00 00              ..h.........    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0a 00 68 11 01 00 00 00 e9 f2 00 00              ..h.........    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0a 00 68 11 01 00 00 00 62 f3 00 00              ..h.....b...    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0e 00 68 11 02 00 00 00 63 f3 00 00 70 f3 00 00  ..h.....c...p...
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0a 00 68 11 01 00 00 00 64 f3 00 00              ..h.....d...    
0009:fixme:dbghelp_msc:codeview_snarf Unsupported symbol id 1168
0009:fixme:dbghelp_msc:dump 00000000: 0e 00 68 11 02 00 00 00 63 f3 00 00 6f f3 00 00  ..h.....c...o...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Could not auto detect a chrome executable"', src\libcore\result.rs:1189:5

But the same code works on x64 gnu linux.

**Comment by abzh423** [comment]
Just install chrome, https://geekflare.com/install-chromium-ubuntu-centos/

**Comment by abzh423** [comment]
I guess for now that's the solution in some cases.

**Comment by alexzanderr** [comment]
i asked a question, i didnt mention a solution

**Comment by abzh423** [comment]
No, I don't think it does install the browser automatically.

**Comment by alexzanderr** [comment]
no fish.
