### ISSUE TITLE
Allow preloading extensions

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#2]
via [reddit](https://www.reddit.com/r/rust/comments/aqgsxk/announcing_the_headless_chrome_crate_puppeteer/egfxphb/)

It should be as easy as passing along a filepath to a new argument (`--load-extension=`) here:

https://github.com/atroche/rust-headless-chrome/blob/2cc5bbb42210e78f6f4c2dfc573217b86692ee9b/src/process.rs#L106-L112

**Comment by max-frai** [comment]
Yep! Extensions are often used to modify pages or remove some limitations.

**Comment by ravi0213** [comment]
Hi, could you please assign this issue to me?

**Comment by atroche** [comment]
@ravi0213 yep!

**Comment by atroche** [comment]
@ravi0213 huh, any idea why I can't assign it to you?

<img width="402" alt="image" src="https://user-images.githubusercontent.com/29839/52820720-daac5980-3100-11e9-8f44-20174e772644.png">

In any case, it's yours if you want it :)

**Comment by scottlamb** [comment]
As far as I can tell, on github you can only assign issues / request PR reviews from project owners. I've run into the same thing in a project of mine, and it's super annoying.

**Comment by ravi0213** [comment]
@atroche thank you, I’ll start working on it asap :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atroche** [comment]
Great! Feel free to email me or comment here if you have any trouble.
