### ISSUE TITLE
Make the `ws_url_from_output` function return a Url from the url crate

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#20]
https://github.com/atroche/rust-headless-chrome/blob/1f29ff6d3079fc12c3968994ea3309e7c6f70d28/src/process.rs#L145

Like this:

```rust
let url = Url::parse("ws://127.0.0.1/devtools/etc").unwrap();
```

And then in here we can call this constructor instead of `new`:

```rust
let client = ClientBuilder::from_url(&url)?;
```
https://github.com/atroche/rust-headless-chrome/blob/8175e58d1a541f12c90d00159615d2aac8af3e9c/src/web_socket_connection.rs#L72

**Comment by mdrokz** [comment]
merged #263
