### ISSUE TITLE
Question: is there a way to get the CSS styles for a DOM element?

### ISSUE THREAD

**Issue by uynap** [atroche/rust-headless-chrome#217]
For example, I want to list all the CSS styles for the DOM `//div[@id="content"]/div[@id="a"]` on the page.

I can do it by using https://godoc.org/github.com/chromedp/chromedp#ComputedStyle, which is built in Golang with Chrome DevTools Protocol. I was wondering is there a similar way to achieve it in Rust?

**Comment by awikman** [comment]
As far as I know, it hasn't been implemented. We'd need to implement this:
https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-getComputedStyleForNode

**Comment by mdrokz** [comment]
> For example, I want to list all the CSS styles for the DOM `//div[@id="content"]/div[@id="a"]` on the page.
> 
> I can do it by using https://godoc.org/github.com/chromedp/chromedp#ComputedStyle, which is built in Golang with Chrome DevTools Protocol. I was wondering is there a similar way to achieve it in Rust?

I have implemented a method called `get_computed_styles` on the Element struct, which will allow you to get all the styles on the element. #259
