### ISSUE TITLE
unknown variant '::marker'

### ISSUE THREAD

**Issue by juma121** [atroche/rust-headless-chrome#227]
Hello, 

Whenever I use tab.wait_for_element('<elementname>') and there is the ::marker pseudo Element in the website-dom I get the following Error.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `marker`, expected one of `first-line`, `first-letter`, `before`, `after`, `backdrop`, `selection`, `first-line-inherited`, `scrollbar`, `scrollbar-thumb`, `scrollbar-button`, `scrollbar-track`, `scrollbar-track-piece`, `scrollbar-corner`, `resizer`, `input-list-button`", line: 0, column: 0)', /usr/local/cargo/git/checkouts/rust-headless-chrome-fd32a97e7a7fa8b4/1f63d69/src/protocol/mod.rs:90:70

Is there any way to extend the project with the ::marker element in order to parse the webpages that contain this element?

Could not find a workaround to solve the problem myself using the Rust backtrace. Hopefully someone can help me out on this.

**Comment by mdrokz** [comment]
> Hello,
> 
> Whenever I use tab.wait_for_element('') and there is the ::marker pseudo Element in the website-dom I get the following Error.
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `marker`, expected one of `first-line`, `first-letter`, `before`, `after`, `backdrop`, `selection`, `first-line-inherited`, `scrollbar`, `scrollbar-thumb`, `scrollbar-button`, `scrollbar-track`, `scrollbar-track-piece`, `scrollbar-corner`, `resizer`, `input-list-button`", line: 0, column: 0)', /usr/local/cargo/git/checkouts/rust-headless-chrome-fd32a97e7a7fa8b4/1f63d69/src/protocol/mod.rs:90:70
> 
> Is there any way to extend the project with the ::marker element in order to parse the webpages that contain this element?
> 
> Could not find a workaround to solve the problem myself using the Rust backtrace. Hopefully someone can help me out on this.

Hello,can you provide me with the website link that you are scraping. so i can debug t he issue.

**Comment by juma121** [comment]
Fix was already merged. Is working now.

**Comment by mdrokz** [comment]
> Fix was already merged. Is working now.

I see, then i will close this issue.
