### ISSUE TITLE
Ideas on not requiring a binary to use? Abandonware?

### ISSUE THREAD

**Issue by seenickcode** [atroche/rust-headless-chrome#228]
I'm looking to use this in a docker-compose file so I can run integration tests. Is there a way this can simply avoid looking for a binary and just connect to a port/server somehow or at least a binary running in another container? Thanks

**Comment by sdimkov** [comment]
AFAIK you can't connect to a remote chrome instance. It should be relatively easy to update the `Browser` and `Process` impls to support it. 

The bigger issue is that this project seems abandoned by its maintainer. You could try instead [Thirtyfour](https://github.com/stevepryde/thirtyfour). It's based on Selenium so you'll need to also run chromedriver but it supports a remote connection out of the box.

**Comment by seenickcode** [comment]
Hi see I’ll check it out, thank you very much. I was looking for a pure
Rust solution. Ended up using plain old Cypress.

**Comment by mdrokz** [comment]
> AFAIK you can't connect to a remote chrome instance. It should be relatively easy to update the `Browser` and `Process` impls to support it.
> 
> The bigger issue is that this project seems abandoned by its maintainer. You could try instead [Thirtyfour](https://github.com/stevepryde/thirtyfour). It's based on Selenium so you'll need to also run chromedriver but it supports a remote connection out of the box.

Hello, i think this pr implemented remote connection support - https://github.com/atroche/rust-headless-chrome/pull/107

**Comment by mdrokz** [comment]
closing this because of #107
