### ISSUE TITLE
Support passing arguments to call_js_fn

### ISSUE THREAD

**Issue by agentydragon** [atroche/rust-headless-chrome#231]
Hi! Thanks for the package :)

`callFunctionOn` supports passing parameters to the called function: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-callFunctionOn

Unfortunately, `call_js_fn` does not currently support that.

I want to pass dynamic strings (or more complex stuff ideally) to the JS function. For now, I can just escape the strings and concat the function source code together, but it's a bit hacky.

**Comment by mdrokz** [comment]
> Hi! Thanks for the package :)
> 
> `callFunctionOn` supports passing parameters to the called function: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-callFunctionOn
> 
> Unfortunately, `call_js_fn` does not currently support that.
> 
> I want to pass dynamic strings (or more complex stuff ideally) to the JS function. For now, I can just escape the strings and concat the function source code together, but it's a bit hacky.

I'm working on this feature and will merge it when ready.

**Comment by mdrokz** [comment]
merged #256
