### ISSUE TITLE
I can't use the Tab::click_point function.

### ISSUE THREAD

**Issue by myyrakle** [atroche/rust-headless-chrome#246]
https://docs.rs/headless_chrome/0.9.0/headless_chrome/browser/tab/struct.Tab.html#method.click_point

The Tab::click_point function takes a Point type value as a parameter, 
but cannot be used because the browser::tab::point::Point type is private.

I ask for confirmation of this part.

**Comment by mdrokz** [comment]
> https://docs.rs/headless_chrome/0.9.0/headless_chrome/browser/tab/struct.Tab.html#method.click_point
> 
> The Tab::click_point function takes a Point type value as a parameter,
> but cannot be used because the browser::tab::point::Point type is private.
> 
> I ask for confirmation of this part.

the point module is now public and you can access the Point struct on the master branch. https://github.com/atroche/rust-headless-chrome/blob/master/src/browser/tab/mod.rs see here

**Comment by myyrakle** [comment]
Thanks for the kind answer.
