### ISSUE TITLE
Can i use this for creating whatsapp BOT?

### ISSUE THREAD

**Issue by miqbalrr** [atroche/rust-headless-chrome#248]
these are my BOT requirements:
1. scanning whatsapp barcode
2. sending a new message to new number (text, image, documents)
3. handling multiple whatsapp account

Thankyou

**Comment by mdrokz** [comment]
> these are my BOT requirements:
> 
> 1. scanning whatsapp barcode
> 2. sending a new message to new number (text, image, documents)
> 3. handling multiple whatsapp account
> 
> Thankyou

1. i dont know about scanning the barcode
2. you could do that by selecting elements and clicking on them
3. you can do this by creating incognito context and opening new windows.

**Comment by miqbalrr** [comment]
How about these missing features ?
1. Dealing with frames
2. Handling file picker / chooser interactions

do the library will cover that missing too ? because i think i need this

**Comment by mdrokz** [comment]
> How about these missing features ?
> 1. Dealing with frames
> 2. Handling file picker / chooser interactions
> 
> do the library will cover that missing too ? because i think i need this

I'm trying to implement the missing features.

1.  Are there any iframes in whatsapp web?
2. I Will try to implement this soon
