### ISSUE TITLE
How to implement authentication 

### ISSUE THREAD

**Issue by initprism** [atroche/rust-headless-chrome#253]
I know that basic auth is not currently implemented. 
 
How can I implement basic and digest auth?  or  set extra headers ?

nodejs: 
`await page.authenticate({
    username: username,
    password: password
})
`

Thanks for making such a great package.

**Comment by mdrokz** [comment]
> I know that basic auth is not currently implemented.
> 
> How can I implement basic and digest auth? or set extra headers ?
> 
> nodejs:
> `await page.authenticate({ username: username, password: password }) `
> 
> Thanks for making such a great package.

Hi i just merged a pull request that implements setting extra headers and authentication. use the library from git instead of crates.io

**Comment by mdrokz** [comment]
If there are no problems, i will close this now.
