### ISSUE TITLE
how to construct a KeyDefinition?

### ISSUE THREAD

**Issue by pypypypypypypypypyp** [atroche/rust-headless-chrome#276]
I'm trying to call Tab::press_key but the git version uses a KeyDefinition instead of &str and KeyDefinition is in a private module which is seemingly not re-exported anywhere?

**Comment by mdrokz** [comment]
> I'm trying to call Tab::press_key but the git version uses a KeyDefinition instead of &str and KeyDefinition is in a private module which is seemingly not re-exported anywhere?

Hi, sorry for late reply im fixing this currently.

**Comment by mdrokz** [comment]
fixed with #279
