### ISSUE TITLE
Handle (admittedly unlikely) case where child_process.stderr is None

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#28]
Currently we just call `unwrap` on it:
https://github.com/atroche/rust-headless-chrome/blob/1f29ff6d3079fc12c3968994ea3309e7c6f70d28/src/process.rs#L160

**Comment by r-darwish** [comment]
I think that unwrapping in this scenario is fine, since we explicitly launch the process with piped stderr. Using panics for errors which can probably only be caused by a bug in the crate is considered okay, I think.

**Comment by lukaslueg** [comment]
The only time this `Option` can be `None` is if we didn't pipe `stderr` in the first place or if we called `.take()` on the `Option`. Both is a logic error in the code itself, so an `unwrap()` is entirely justified.

**Comment by atroche** [comment]
Thanks guys, that makes sense.
