### ISSUE TITLE
find_elements is very slow

### ISSUE THREAD

**Issue by mockfox** [atroche/rust-headless-chrome#281]
Running tab.find_elements() is extremely slow. It takes between 60-100 seconds to find ~100 elements.

**Comment by mdrokz** [comment]
> Running tab.find_elements() is extremely slow. It takes between 60-100 seconds to find ~100 elements.

Hi, can you post the code please ?

**Comment by mockfox** [comment]
Sorry for the slow response. I figured out it was an issue with my processor, not this crate.

**Comment by mockfox** [comment]
It is still quite slow though. I am just running a simple tab.find_elements on a page and pulling out some anchor elements from within a container (`tab.find_elements("#container a")`). It takes ~15 seconds to run. In Javascript, it would work almost instantaneously.

**Comment by mockfox** [comment]
This might just be related to my hardware / GPU acceleration for me. Launching with `--disable-gpu` seems to help.

**Comment by sanderPostma** [comment]
@mockfox 
I have the same issue on both a windows machine and a raspberry pi. I've added to the LaunchOptionsBuilder:
 .args(vec![
            &OsStr::new("--disable-gpu")])
but that did not do anything.
Scanning a simple table takes ~67 seconds. On the pi like 5 more. Test project on Github:
https://github.com/sanderPostma/chrome-headless-perf

**Comment by escritorio-gustavo** [comment]
This issue still persists, I executed the test @sanderPostma linked to and it's taking 66 seconds on my computer.

And the table isn't even very large, (8x25). `find_elements` didn't even work for me, I had to change it to `wait_for_elements`, and it took 43 seconds.

I also had to change the xpaths to CSS selectors because it wouldn't work with the xpaths

**Comment by jellybobbin** [comment]
I have the same problem
