### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by teddywing** [atroche/rust-headless-chrome#282]
I see the [`Cargo.toml`](https://github.com/atroche/rust-headless-chrome/blob/09747c06c77a305adf2421d67d74ae69c0430225/Cargo.toml#L7) indicates this project is licensed under the MIT license, but I couldn't find a license file.

Would it be possible to add a license file that includes the copyright required by the MIT license (https://choosealicense.com/licenses/mit/)?

**Comment by elpiel** [comment]
I've opened a PR for this @teddywing.
