### ISSUE TITLE
Request to add an option to disable all the wait timeout

### ISSUE THREAD

**Issue by HollowMan6** [atroche/rust-headless-chrome#287]
I suggest adding an option to disable all the timeout for places that use `Wait::with_timeout(x).until` so that they will wait forever to increase the robustness of the program.

In my case, errors related to timeouts are mostly not caused by page crashes, but just a lagging computer. I wrote a program that generates PDF from web pages, I can fix the errors https://github.com/HollowMan6/mdbook-pdf/runs/4896621124?check_suite_focus=true with the commit in my fork setting those timeouts to forever https://github.com/HollowMan6/rust-headless-chrome/commit/0c5d707b28bdc577b5d386bc2e90d91b10143116 , and the program never run forever actually, and successfully finished.

So I would really appreciate to have such a option, thanks.

**Comment by mdrokz** [comment]
> I suggest adding an option to disable all the timeout for places that use `Wait::with_timeout(x).until` so that they will wait forever to increase the robustness of the program.
> 
> In my case, errors related to timeouts are mostly not caused by page crashes, but just a lagging computer. I wrote a program that generates PDF from web pages, I can fix the errors https://github.com/HollowMan6/mdbook-pdf/runs/4896621124?check_suite_focus=true with the commit in my fork setting those timeouts to forever [HollowMan6@0c5d707](https://github.com/HollowMan6/rust-headless-chrome/commit/0c5d707b28bdc577b5d386bc2e90d91b10143116) , and the program never run forever actually, and successfully finished.
> 
> So I would really appreciate to have such a option, thanks.

Hi, i feel having the timer wait forever is dangerous, instead of that how about having a global setting for all timers that you can control ?

**Comment by HollowMan6** [comment]
> Hi, i feel having the timer wait forever is dangerous, instead of that how about having a global setting for all timers that you can control ?

Thanks for your reply. It'll be definitely great if there's a global setting to configure for all timers.

**Comment by mdrokz** [comment]
> > Hi, i feel having the timer wait forever is dangerous, instead of that how about having a global setting for all timers that you can control ?
> 
> Thanks for your reply. It'll be definitely great if there's a global setting to configure for all timers.

I added a default timeout for `wait_until_navigated` and all of the other timers can be controlled with `set_default_timeout` method
