### ISSUE TITLE
How to embed browser binary?

### ISSUE THREAD

**Issue by muscache** [atroche/rust-headless-chrome#295]
Is it possible to embed a browser binary using eg, the [include_bytes!](https://doc.rust-lang.org/std/macro.include_bytes.html) macro?
My use-case is to lock browser version and prevent tampering, such as spinning up a fake or old browser instance.

Thanks

Edit: There is a project, https://github.com/chromiumembedded/cef for embedding chromium. But it seems there is no Rust support.

**Comment by mdrokz** [comment]
> Is it possible to embed a browser binary using eg, the [include_bytes!](https://doc.rust-lang.org/std/macro.include_bytes.html) macro? My use-case is to lock browser version and prevent tampering, such as spinning up a fake or old browser instance.
> 
> Thanks
> 
> Edit: There is a project, https://github.com/chromiumembedded/cef for embedding chromium. But it seems there is no Rust support.

you could use the in built fetcher and specify a location to save the chromium binary and then use `include_bytes` macro to include the binary in your program.

**Comment by muscache** [comment]
Thanks. I'll try this and report

**Comment by muscache** [comment]
Ended up using CEF's C++ bindings
