### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by elpiel** [atroche/rust-headless-chrome#296]
I see that there hasn't been a new release since 2019 and that there has been quite some work done since then.

Is it possible to create a new release?

**Comment by 3vts** [comment]
I think it is worth to either fork/create new crate/release/archive. Or just release but the community needs this and the official way to go to install libs is through crates.io

**Comment by 3vts** [comment]
This one can be closed as well @mdrokz

**Comment by frederikhors** [comment]
I think this can be closed today.

**Comment by elpiel** [comment]
I agree. There are still some bugs and things I would like to be fixed but I will open a PR for that and another issue to discuss opening multiple tabs and parallel processing.
