### ISSUE TITLE
you promised chromium will be auto installed, but you didnt mention HOW

### ISSUE THREAD

**Issue by alexzanderr** [atroche/rust-headless-chrome#303]
here's what you mentioned:
`"By default, headless_chrome will download a compatible version of chrome to XDG_DATA_HOME (or equivalent on Windows/Mac)."` (from readme)

i've installed the crate, ran the example on readme and got this error: `"Could not auto detect a chrome executable"`, yes it could not detect, but it also wouldnt install it.

here is no auto install here:
```rust
/// Returns the path to Chrome's executable.
///
/// If the `CHROME` environment variable is set, `default_executable` will
/// use it as the default path. Otherwise, the filenames `google-chrome-stable`
/// `chromium`, `chromium-browser`, `chrome` and `chrome-browser` are
/// searched for in standard places. If that fails,
/// `/Applications/Google Chrome.app/...` (on MacOS) or the registry (on Windows)
/// is consulted. If all of the above fail, an error is returned.
pub fn default_executable() -> Result<std::path::PathBuf, String> {
    if let Ok(path) = std::env::var("CHROME") {
        if std::path::Path::new(&path).exists() {
            return Ok(path.into());
        }
    }

    for app in &[
        "google-chrome-stable",
        "chromium",
        "chromium-browser",
        "chrome",
        "chrome-browser",
    ] {
        if let Ok(path) = which(app) {
            return Ok(path);
        }
    }

    #[cfg(target_os = "macos")]
    {
        let default_paths = &["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"][..];
        for path in default_paths {
            if std::path::Path::new(path).exists() {
                return Ok(path.into());
            }
        }
    }

    #[cfg(windows)]
    {
        use crate::browser::process::get_chrome_path_from_registry;

        if let Some(path) = get_chrome_path_from_registry() {
            if path.exists() {
                return Ok(path);
            }
        }
    }

    Err("Could not auto detect a chrome executable".to_string())
}
```

but i found this in the source
```rust
/// You can use [LaunchOptions](../process/LaunchOptions.struct.html) to automatically
/// download a revision of Chromium that has a compatible API into your `$XDG_DATA_DIR`. 
```

i dont know to make that happen and there is no example in the examples folder on how to make launch-options in order to auto install the browser.

please make more documentation.

**Comment by mdrokz** [comment]
> here's what you mentioned: `"By default, headless_chrome will download a compatible version of chrome to XDG_DATA_HOME (or equivalent on Windows/Mac)."` (from readme)
> 
> i've installed the crate, ran the example on readme and got this error: `"Could not auto detect a chrome executable"`, yes it could not detect, but it also wouldnt install it.
> 
> here is no auto install here:
> 
> ```rust
> /// Returns the path to Chrome's executable.
> ///
> /// If the `CHROME` environment variable is set, `default_executable` will
> /// use it as the default path. Otherwise, the filenames `google-chrome-stable`
> /// `chromium`, `chromium-browser`, `chrome` and `chrome-browser` are
> /// searched for in standard places. If that fails,
> /// `/Applications/Google Chrome.app/...` (on MacOS) or the registry (on Windows)
> /// is consulted. If all of the above fail, an error is returned.
> pub fn default_executable() -> Result<std::path::PathBuf, String> {
>     if let Ok(path) = std::env::var("CHROME") {
>         if std::path::Path::new(&path).exists() {
>             return Ok(path.into());
>         }
>     }
> 
>     for app in &[
>         "google-chrome-stable",
>         "chromium",
>         "chromium-browser",
>         "chrome",
>         "chrome-browser",
>     ] {
>         if let Ok(path) = which(app) {
>             return Ok(path);
>         }
>     }
> 
>     #[cfg(target_os = "macos")]
>     {
>         let default_paths = &["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"][..];
>         for path in default_paths {
>             if std::path::Path::new(path).exists() {
>                 return Ok(path.into());
>             }
>         }
>     }
> 
>     #[cfg(windows)]
>     {
>         use crate::browser::process::get_chrome_path_from_registry;
> 
>         if let Some(path) = get_chrome_path_from_registry() {
>             if path.exists() {
>                 return Ok(path);
>             }
>         }
>     }
> 
>     Err("Could not auto detect a chrome executable".to_string())
> }
> ```
> 
> but i found this in the source
> 
> ```rust
> /// You can use [LaunchOptions](../process/LaunchOptions.struct.html) to automatically
> /// download a revision of Chromium that has a compatible API into your `$XDG_DATA_DIR`. 
> ```
> 
> i dont know to make that happen and there is no example in the examples folder on how to make launch-options in order to auto install the browser.
> 
> please make more documentation.

you have to specify the fetch feature like this 
```rust
[dependencies]
serde = '1'
serde_json = '1'
headless_chrome = {git = 'https://github.com/atroche/rust-headless-chrome', features = ['fetch']}
```

**Comment by alexzanderr** [comment]
i had fetch feature ON, didnt work

**Comment by mdrokz** [comment]
> i had fetch feature ON, didnt work

which OS are you using and your using the git version right?

**Comment by alexzanderr** [comment]
wait, so if i put this
```toml
headless_chrome = {git = 'https://github.com/atroche/rust-headless-chrome', features = ['fetch']}
```
in cargo toml and just run the minimal example from readme, it should work ?

**Comment by mdrokz** [comment]
> wait, so if i put this
> 
> ```toml
> headless_chrome = {git = 'https://github.com/atroche/rust-headless-chrome', features = ['fetch']}
> ```
> 
> in cargo toml and just run the minimal example from readme, it should work ?

yes i tested that with my own project

**Comment by alexzanderr** [comment]
first time i tried with this `Cargo.toml`

```toml
headless_chrome = {version = 'latest(whatever)', features = ['fetch']}
```
and it didnt work.

must it be from `git` ?

**Comment by mdrokz** [comment]
> first time i tried with this `Cargo.toml`
> 
> ```toml
> headless_chrome = {version = 'latest(whatever)', features = ['fetch']}
> ```
> and it didnt work.
> 
> must it be from `git` ?

Yes the git version is the latest and i tried it with the git version in my project.

**Comment by alexzanderr** [comment]
nice

**Comment by amaurym** [comment]
Any change we can get this in a tagged version?
