### ISSUE TITLE
Huge bunch of linter warnings

### ISSUE THREAD

**Issue by djfm** [atroche/rust-headless-chrome#313]
They hurt my eyes ;)

Would you accept a PR fixing them?

Should not be too hard with vscode and rust-analyzer who is not bad at refactoring.

**Comment by mdrokz** [comment]
> They hurt my eyes ;)
> 
> Would you accept a PR fixing them?
> 
> Should not be too hard with vscode and rust-analyzer who is not bad at refactoring.

Sure, i didnt get much time to fix all of those linter warnings if somebody makes an PR i will merge it

**Comment by djfm** [comment]
Ah but is `protocol.rs` auto-generated or not?

**Comment by Oyami-Srk** [comment]
`protocol.rs` is auto-generated.

Add`#[allow(unused)]`, `#[allow(non_camel_case_types)]` and `#[allow(non_snake_case)]` at the top of `protocol.rs` would suppress most of warnings.

True cleanup may require a overall renaming of types

https://github.com/Oyami-Srk/auto_generate_cdp/commit/004b3d8376ad32c36aecdb5bc273b3313bdcb9b6

**Comment by djfm** [comment]
Yes, the directives sound like a much safer solution for now!

**Comment by mdrokz** [comment]
completed with #345 and https://github.com/mdrokz/auto_generate_cdp/commit/973449ac6d7ed5258eaa75e5fb53fd8c5972fa68
