### ISSUE TITLE
Tabs become unresponsive if Browser is dropped

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#32]
If we have an instance of `Browser`, create a `Tab`, navigate somewhere, `drop()` the `Browser` and continue using the `Tab`, the process starts consuming 100% CPU and becomes unresponsive.

Demonstrated [here](https://github.com/lukaslueg/rust-headless-chrome/blob/d4b5421ae45f41be4aaf53fba80c35367132ca8e/tests/simple.rs#L21-L23) if we `drop()` the `_browser` before calling `wait_for_element()` on the `tab`.

**Comment by atroche** [comment]
Got an hour long flight this arvo; should be able to fix this up in that time.
