### ISSUE TITLE
Some code examples are outdated

### ISSUE THREAD

**Issue by qiaoruntao** [atroche/rust-headless-chrome#321]
Hello, thanks for your great work on this repository.
But I find the quick start code example is not runnable so I updated it, I also fixed another outdated code example in `lib.rs`. 
I also change the languange of `Cargo.toml` from `rust` to `toml`, which should be correctly recognized by editors now.
The fixes are in pull request #320 , you can merge it if you find it useful.
Thanks!

**Comment by mdrokz** [comment]
merged #320
