### ISSUE TITLE
Adress vulnerabilities reported by `cargo audit`

### ISSUE THREAD

**Issue by azatoth** [atroche/rust-headless-chrome#322]
Running `cargo audit` will result in following vulnerabilities listed: 

<details>
<summary>
Output from <tt>cargo audit</tt>
</summary>

```text
azatoth@azaboxen:~/build/rust-websocket «master u=»$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 433 security advisories (from /home/azatoth/.cargo/advisory-db)
    Updating crates.io index
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (132 crate dependencies)
Crate:     hyper
Version:   0.10.16
Title:     Integer overflow in `hyper`'s parsing of the `Transfer-Encoding` header leads to data loss
Date:      2021-07-07
ID:        RUSTSEC-2021-0079
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0079
Solution:  Upgrade to >=0.14.10
Dependency tree:
hyper 0.10.16
└── websocket 0.26.5

Crate:     hyper
Version:   0.10.16
Title:     Lenient `hyper` header parsing of `Content-Length` could allow request smuggling
Date:      2021-07-07
ID:        RUSTSEC-2021-0078
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0078
Solution:  Upgrade to >=0.14.10

Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── hyper 0.10.16
    └── websocket 0.26.5

Crate:     tokio
Version:   0.1.22
Title:     Data race when sending and receiving after closing a `oneshot` channel
Date:      2021-11-16
ID:        RUSTSEC-2021-0124
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0124
Solution:  Upgrade to >=1.8.4, <1.9.0 OR >=1.13.1
Dependency tree:
tokio 0.1.22
├── websocket-base 0.26.5
│   └── websocket 0.26.5
└── websocket 0.26.5

Crate:     net2
Version:   0.2.37
Warning:   unmaintained
Title:     `net2` crate has been deprecated; use `socket2` instead
Date:      2020-05-01
ID:        RUSTSEC-2020-0016
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.37
├── miow 0.2.2
│   └── mio 0.6.23
│       ├── tokio-tcp 0.1.4
│       │   ├── websocket-base 0.26.5
│       │   │   └── websocket 0.26.5
│       │   ├── websocket 0.26.5
│       │   └── tokio 0.1.22
│       │       ├── websocket-base 0.26.5
│       │       └── websocket 0.26.5
│       ├── tokio-reactor 0.1.12
│       │   ├── websocket 0.26.5
│       │   ├── tokio-tcp 0.1.4
│       │   └── tokio 0.1.22
│       └── tokio 0.1.22
└── mio 0.6.23

error: 4 vulnerabilities found!
warning: 1 allowed warning found
```

</details>

Most of the issues seems to be related to the use of [`websocket`](https://github.com/websockets-rs/rust-websocket), and looking over there, it's evident they have fallen back on the maintenance, and even recommends people using other websocket libraries.

Question then is if it's feasible for `headless-chrome` to switch from `websocket` to for example [`tungstenite`](https://crates.io/crates/tungstenite) or [`tokio-tungstenite`](https://crates.io/crates/tokio-tungstenite)

**Comment by mdrokz** [comment]
> Running `cargo audit` will result in following vulnerabilities listed:
> 
> Output from cargo audit
> Most of the issues seems to be related to the use of [`websocket`](https://github.com/websockets-rs/rust-websocket), and looking over there, it's evident they have fallen back on the maintenance, and even recommends people using other websocket libraries.
> 
> Question then is if it's feasible for `headless-chrome` to switch from `websocket` to for example [`tungstenite`](https://crates.io/crates/tungstenite) or [`tokio-tungstenite`](https://crates.io/crates/tokio-tungstenite)

I tried to switch to updated libraries like tungstenite, but it wasnt feasible if i switch it to tungstenite i would have to rewrite the whole library to be async, because tungstenite doesnt support dual channels for tcp.

**Comment by AngeloCore** [comment]
> tungstenite

i am new to rust, but can't you use `tungstenite` instead of `tokio-tungstenite`?

**Comment by Sytten** [comment]
@mdrokz AFAIK tungstenite is not async so there should not be any issue moving to it

**Comment by mdrokz** [comment]
> @mdrokz AFAIK tungstenite is not async so there should not be any issue moving to it

Not sure if it supports dual channels i couldn't find it when i tried to migrate

**Comment by Sytten** [comment]
I just tried to migrate and indeed only the async version supports the split of stream. That would mean it would require to re-architecture the crate around that limitation or move to async.

**Comment by mdrokz** [comment]
> I just tried to migrate and indeed only the async version supports the split of stream. That would mean it would require to re-architecture the crate around that limitation or move to async.

Yep exactly

**Comment by Sytten** [comment]
I can understand the hesitancy to move to async even if most network crates now are async. Even the websocket crate is async with a tokio sync wrapper around it. I had this exact discussion with another crate maintainer (secret service) like yesterday. Hopefully the state of sync/async compatibility gets better next year.

On my side I am strongly considering building an async headless chrome crate with essentially the same api as this one.

**Comment by mdrokz** [comment]
> I can understand the hesitancy to move to async even if most network crates now are async. Even the websocket crate is async with a tokio sync wrapper around it. I had this exact discussion with another crate maintainer (secret service) like yesterday. Hopefully the state of sync/async compatibility gets better next year.
> 
> On my side I am strongly considering building an async headless chrome crate with essentially the same api as this one. Edit: I found out about https://github.com/mattsse/chromiumoxide, I am just going to port the fetcher and use that.

its too much work to shift it to async and right now the library is in a stable state and async is also harder to debug this is why im hesitant to migrate it to an async library

**Comment by AngeloCore** [comment]
nah please, dont switch to async!... i dont want tokio in my project, if i want async i would have used `chromiumoxide`

**Comment by mdrokz** [comment]
> nah please, dont switch to async!... i dont want tokio in my project, if i want async i would have used `chromiumoxide`

#349 doesnt switch the API to async it just wraps it an async runtime, and we need it to fix the security vulnerability
