### ISSUE TITLE
How to block/cancel a request within the interceptor?

### ISSUE THREAD

**Issue by lamualfa** [atroche/rust-headless-chrome#327]
Should I return a `Response(400)` to cancel the request?

**Comment by mdrokz** [comment]
> Should I return a `Response(400)` to cancel the request?

Hi sorry for late reply you can check this

https://github.com/atroche/rust-headless-chrome/blob/f8012ec4ed867ccc0efa6b262723363afd775011/src/browser/tab/mod.rs#L350-L352

you can return `RequestPausedDecision::Fail`
