### ISSUE TITLE
Closing a tab somehow possible?

### ISSUE THREAD

**Issue by inzanez** [atroche/rust-headless-chrome#329]
Hi

I see that it is quite easy to open new tabs. Is there also a way of closing them again? I suspect that Chrome will reach a limit of open tabs at some point...

**Comment by mdrokz** [comment]
> Hi
> 
> I see that it is quite easy to open new tabs. Is there also a way of closing them again? I suspect that Chrome will reach a limit of open tabs at some point...

https://github.com/atroche/rust-headless-chrome/blob/f8012ec4ed867ccc0efa6b262723363afd775011/src/browser/tab/mod.rs#L1427 have you checked this method ?

**Comment by inzanez** [comment]
@mdrokz No,...I did not. I must have missed it, I looked through the documentation but didn't find it there. So maybe this is new and not yet in the released crate,...or it somehow didn't make it into documentation. Thanks! :-)
