### ISSUE TITLE
How do I set HTML for a tab?

### ISSUE THREAD

**Issue by kimyvgy** [atroche/rust-headless-chrome#336]
I want to set HTML into a tab directly. After that, call `capture_screenshot` to get an image.

=> How do I set HTML for a tab?

**Comment by mdrokz** [comment]
> I want to set HTML into a tab directly. After that, call `capture_screenshot` to get an image.
> 
> => How do I set HTML for a tab?

What do you mean by setting html directly in tab, do you mean evaluating js ?

**Comment by kimyvgy** [comment]
@mdrokz I have a HTML string. I want to convert these string to Image file instead of PDF:
```rust
use wkhtmltopdf::*;

let html = r#"<html><body><div>foo</div></body></html>"#;
let mut pdf_app = PdfApplication::new().expect("Failed to init PDF application");
let mut pdfout = pdf_app.builder()
    .orientation(Orientation::Landscape)
    .margin(Size::Inches(2))
    .title("Awesome Foo")
    .build_from_html(&html)
    .expect("failed to build pdf");

pdfout.save("foo.pdf").expect("failed to save foo.pdf");
```

**Comment by kimyvgy** [comment]
It seems `ImageApplication` does not support `build_from_html` like PdfApplication.

**Comment by mdrokz** [comment]
> @mdrokz I have a HTML string. I want to convert these string to Image file instead of PDF:
> 
> ```rust
> use wkhtmltopdf::*;
> 
> let html = r#"<html><body><div>foo</div></body></html>"#;
> let mut pdf_app = PdfApplication::new().expect("Failed to init PDF application");
> let mut pdfout = pdf_app.builder()
>     .orientation(Orientation::Landscape)
>     .margin(Size::Inches(2))
>     .title("Awesome Foo")
>     .build_from_html(&html)
>     .expect("failed to build pdf");
> 
> pdfout.save("foo.pdf").expect("failed to save foo.pdf");
> ```

you can follow this example, get the element you want to append the html to and then call a js function and append the html by passing it as an argument and then you can screenshot it.

```rs
use anyhow::Result;

use headless_chrome::{Browser, LaunchOptions};

fn main() -> Result<()> {
    let browser = Browser::new(
        LaunchOptions::default_builder()
            .build()
            .expect("Could not find chrome-executable"),
    )?;

    let tab = browser.wait_for_initial_tab()?;

    tab.navigate_to("https://www.google.com")
        .expect("failed to navigate");

    tab.wait_until_navigated().unwrap();

    let element = tab.wait_for_xpath("/html/body/div[1]/div[5]/div[1]")?;

    element.call_js_fn(
        "function(...args) {if(arg[0]) {return this.innerText;}}",
        vec![],
        false,
    )?;

    Ok(())
}
```

**Comment by kimyvgy** [comment]
@mdrokz I'm looking for solution to convert HTML string to image. I can do it with Puppeteer in Node.js:
```javascript

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const fileName = 'foo.png';

  await page.setContent(getImageHtml(post));

  const content = await page.$('body');
  const imageBuffer = await content.screenshot({ omitBackground: true });

  fs.writeFileSync(`./public/${fileName}`, imageBuffer);
```

**Comment by kimyvgy** [comment]
@mdrokz Thank you. Let me try it.

**Comment by mdrokz** [comment]
> > @mdrokz I'm looking for solution to convert HTML string to image. I can do it with Puppeteer in Node.js:
> > ```js
> >   const browser = await puppeteer.launch();
> >   const page = await browser.newPage();
> > 
> >   const fileName = 'foo.png';
> > 
> >   await page.setContent(getImageHtml(post));
> > 
> >   const content = await page.$('body');
> >   const imageBuffer = await content.screenshot({ omitBackground: true });
> > 
> >   fs.writeFileSync(`./public/${fileName}`, imageBuffer);
> > ```
> 
> This solution will work for you.
> 
> ```rust
> use anyhow::Result;
> 
> use headless_chrome::{Browser, LaunchOptions};
> 
> use headless_chrome::protocol::cdp::Page::CaptureScreenshotFormatOption;
> 
> fn main() -> Result<()> {
>     let browser = Browser::new(
>         LaunchOptions::default_builder()
>             .build()
>             .expect("Could not find chrome-executable"),
>     )?;
> 
>     let tab = browser.wait_for_initial_tab()?;
> 
>     tab.navigate_to("https://www.google.com")
>         .expect("failed to navigate");
> 
>     tab.wait_until_navigated().unwrap();
> 
>     
>     let html = "<html><head></head><body><div>foo</div></body></html>".to_string();
>     
>     tab.evaluate(&format!(r#"(function() {{
>         let html = "{}";
>         
>         document.open();
>         document.write(html);
>         document.close();
>         
>     }})()"#,html), false)?;
>     
>     let element = tab.find_element("body")?;
> 
>     let bytes = element.capture_screenshot(CaptureScreenshotFormatOption::Png)?;
> 
>     std::fs::write("foo.png", bytes)?;
>     
>     Ok(())
> }
> ```


> 

let me know if it works

**Comment by kimyvgy** [comment]
@mdrokz unresolved import `headless_chrome::protocol::cdp`

It seems `cpd` mod is only available in v1.0.0 which is not released.

**Comment by mdrokz** [comment]
> @mdrokz unresolved import `headless_chrome::protocol::cdp`
> 
> It seems `cpd` mod is only available in v1.0.0 which is not released. 

You can use the git version if you want since it's the latest but you can modify the import to support 0.0.9

**Comment by kimyvgy** [comment]
@mdrokz A blank page is captured. I think the JavaScript is not executed before capturing. Do you have any idea?

```rust
pub use headless_chrome::protocol::cdp::Page::CaptureScreenshotFormatOption as ImageFormat;

pub fn build_from_html(html: &str, format: ImageFormat) -> Vec<u8> {
    let browser = Browser::default().expect("Could not initialize browser");
    let tab = browser.new_tab().expect("Could not open new tab");

    tab.evaluate(&format!(r#"(function() {{
        let html = "{}";

        document.open();
        document.write(html);
        document.close();
    }})()"#,html), false)
        .expect("Could not evaluate JavaScript");

    let element = tab.find_element("body").expect("Failed to find element 'body'");
    let bytes = element.capture_screenshot(format).expect("Failed to capture screenshot");

    bytes
}

fn main() {
    // ...
    let html = thumbnail_template.render().unwrap();
    let bytes = build_from_html(&html, ImageFormat::Jpeg);

    std::fs::write("foo.jpg", bytes.clone()).expect("Failed to write foo.jpg file");
}
```

**Comment by mdrokz** [comment]
> @mdrokz A blank page is captured. I think the JavaScript is not executed before capturing. Do you have any idea?
> 
> ```rust
> pub use headless_chrome::protocol::cdp::Page::CaptureScreenshotFormatOption as ImageFormat;
> 
> pub fn build_from_html(html: &str, format: ImageFormat) -> Vec<u8> {
>     let browser = Browser::default().expect("Could not initialize browser");
>     let tab = browser.new_tab().expect("Could not open new tab");
> 
>     tab.evaluate(&format!(r#"(function() {{
>         let html = "{}";
> 
>         document.open();
>         document.write(html);
>         document.close();
>     }})()"#,html), false)
>         .expect("Could not evaluate JavaScript");
> 
>     let element = tab.find_element("body").expect("Failed to find element 'body'");
>     let bytes = element.capture_screenshot(format).expect("Failed to capture screenshot");
> 
>     bytes
> }
> 
> fn main() {
>     // ...
>     let html = thumbnail_template.render().unwrap();
>     let bytes = build_from_html(&html, ImageFormat::Jpeg);
> 
>     std::fs::write("foo.jpg", bytes.clone()).expect("Failed to write foo.jpg file");
> }
> ```

Try turning off headless mode and see what's happening

**Comment by kimyvgy** [comment]
@mdrokz I escape the html string then the image renders correctly. Thank you so much.
