### ISSUE TITLE
Do not expose internal types, modules or methods

### ISSUE THREAD

**Issue by r-darwish** [atroche/rust-headless-chrome#34]
Currently everything in `lib.rs` is set to `pub`. The crate should only export the types necessary for the user.

**Comment by lukaslueg** [comment]
Yes, there is way too many moving parts between `browser`, `process´, `tab` etc.

**Comment by atroche** [comment]
Yeah, I think some of the modules need to be nested, as well.

**Comment by atroche** [comment]
I reckon this is fixed by https://github.com/atroche/rust-headless-chrome/pull/54
