### ISSUE TITLE
Swap out websocket impl from websocket_rs to tungstenite?

### ISSUE THREAD

**Issue by seanpianka** [atroche/rust-headless-chrome#341]
The `websocket` package has a note in its repository that:
> "Maintainership of this project is slugglish. You may want to use tungstenite or tokio-tungstenite instead."

Upon further inspection, there has been [an open issue](https://github.com/websockets-rs/rust-websocket/issues/262) that the required version of Hyper (0.10.x) is vulnerable to several security vulnerabilities: RUSTSEC-2021-0079, RUSTSEC-2021-0078

Other issues have mention that "rust-websocket is based on long-legacy components and porting it to modern stack may be close to a rewrite," with recommendations to switch to tokio-tungstenite or async-tungstenite. This would allow an update to a modern version of Hyper.

Anyone have an idea of the effort required to gut `websocket`?

**Comment by mdrokz** [comment]
> The `websocket` package has a note in its repository that:
> 
> > "Maintainership of this project is slugglish. You may want to use tungstenite or tokio-tungstenite instead."
> 
> Upon further inspection, there has been [an open issue](https://github.com/websockets-rs/rust-websocket/issues/262) that the required version of Hyper (0.10.x) is vulnerable to several security vulnerabilities: RUSTSEC-2021-0079, RUSTSEC-2021-0078
> 
> Other issues have mention that "rust-websocket is based on long-legacy components and porting it to modern stack may be close to a rewrite," with recommendations to switch to tokio-tungstenite or async-tungstenite. This would allow an update to a modern version of Hyper.
> 
> Anyone have an idea of the effort required to gut `websocket`?

you can see this comment for more info https://github.com/atroche/rust-headless-chrome/issues/322#issuecomment-1220587676

**Comment by mdrokz** [comment]
closing this now refer to #322
