### ISSUE TITLE
Move from websocket to tungstenite 

### ISSUE THREAD

**Issue by sinistersnare** [atroche/rust-headless-chrome#346]
The [`websocket` crate](https://crates.io/crates/websocket) That this project depends on recommends moving away from it, to other projects such as [`tungstenite`](https://crates.io/crates/tungstenite).

Currrently, compiling this crate creates a warning from cargo, due to a transitive dependency on `traitobject 0.1.0`, which is using deprecated Rust features. This warning is directly due to the `websocket` dependency.

**Comment by mdrokz** [comment]
> The [`websocket` crate](https://crates.io/crates/websocket) That this project depends on recommends moving away from it, to other projects such as [`tungstenite`](https://crates.io/crates/tungstenite).
> 
> Currrently, compiling this crate creates a warning from cargo, due to a transitive dependency on `traitobject 0.1.0`, which is using deprecated Rust features. This warning is directly due to the `websocket` dependency.

see #322 #341

**Comment by sinistersnare** [comment]
Ah sorry, I mostly made this as something to close, cause I was going to look to replace this right now. Ill look to close #322 instead
