### ISSUE TITLE
Implement ops::Index ?

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#35]
One could implement `std::ops::Index` for `Tab`, so instead of writing
```rust
tab.wait_for_element("foobar")?
```
we write
```rust
tab["foobar"]
```

The index operation will panic if the underlying `wait_for_element` returns an error (including timeout). IMHO this is acceptable, as `Index` should only be used if you are *sure* that the element is there (like `Vec::get()` vs. `Vec[...]`)

**Comment by atroche** [comment]
Yeah, sounds good to me, especially if it's commonly understood in the community that the indexing operations can panic. I imagine in lots of browser tests they want the test to fail straight away if a particular element isn't found. Hopefully we can make the error message clear.

What do you think, @r-darwish ?

**Comment by r-darwish** [comment]
I don't like the idea. This is something that I would consider in Python, but I don't think it's a good Rust practice.

**Comment by lukaslueg** [comment]
Yeah, I don't really like it either. Yet `wait_for_element()` is basically the equivalent of `get()`. Both `Vec` and `HashMap` (and all the other applicable collections) have an index operation which panics if the item is not there. Simply as a matter of convienience in places where a panic is not the end of the world - tests that is - is makes the code a little more concise.

**Comment by atroche** [comment]
One complication: doing a `find_element` can fail in more ways than the element not being there, e.g. network failure. If we were to implement `Index`, there'd be no way to handle that, right?

**Comment by lukaslueg** [comment]
Yes, if there are possible transient errors involved, there is nothing we can do.
