### ISSUE TITLE
git version depends on auto_generate_cdp 0.4.0 but crates.io version depends on 0.3.4

### ISSUE THREAD

**Issue by seanpianka** [atroche/rust-headless-chrome#353]
There seems to be a mismatch between that appears on git/master and what code was actually published to crates.io.

**Comment by mdrokz** [comment]
> There seems to be a mismatch between that appears on git/master and what code was actually published to crates.io.

yeah i need to fix that but i havent gotten any time i will fix it soon

**Comment by Billy-Sheppard** [comment]
This should be solved with `v1.0.1`
