### ISSUE TITLE
Stealth mode?

### ISSUE THREAD

**Issue by 0wx** [atroche/rust-headless-chrome#358]
Is it possible to implement stealth like [puppeteer-extra-plugin-stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth)?

**Comment by initprism** [comment]
Yeah.. I don't know about the implementation of puppeteer-extra-plugin-stealth, but I think maybe it uses some browser fingerprint to bypass headless and bot detection techniques. And rust-headless-chrome supports base functions that can implement everything.

E.g
In headless mode, `navigator.webdriver` flag is enabled. So you can bypass this by directly modifying the value of `navigator.webdriver`.

```rust
tab.call_method(Page::AddScriptToEvaluateOnNewDocument {
    source: "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});".to_string(),
    world_name: None,
    include_command_line_api: None
})?;
```
