### ISSUE TITLE
Audit/Remove use of thread:sleep

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#45]
There are several places where `thread:sleep()` is used with arbitrary timeout values. If the API is flaky due to timing issues, trying to `wait()` can't possibly fix it because a CPU under load (or a slow CPU) might simply not schedule the blocking thread for that period of time.

All uses of `thread:sleep()` have to be removed.

**Comment by atroche** [comment]
Good call.

**Comment by atroche** [comment]
Aside from the use of `wait_for`, there are now no uses of `thread::sleep` outside of tests:
https://github.com/atroche/rust-headless-chrome/commit/d0a0962e883ca886ab81a0305ca09330b202f255

**Comment by lukaslueg** [comment]
Good thing, closing
