### ISSUE TITLE
Add ability to reload ?

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#47]
There seems to be no way to trigger a "reload" of the current tab. Is there a way to tell a `Tab` to do the equivalent of a true reload (think `F5`) instead of re-navigating?

**Comment by atroche** [comment]
Yeah, should be a pretty simple one too:

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-reload

Would fit in here:
https://github.com/atroche/rust-headless-chrome/blob/95a706ea6a6eaccd365c4983fa6444b0958e992f/src/cdtp/page.rs#L65-L64

**Comment by lukaslueg** [comment]
Closed in #49
