### ISSUE TITLE
Support setCookies

### ISSUE THREAD

**Issue by max-frai** [atroche/rust-headless-chrome#5]
It's useful when page logic is hidden behind authorization. Save / Load cookies from file or byte string will help to achieve this.

**Comment by atroche** [comment]
Good idea, I'd find this useful too (one of my tests involves logging into Dropbox every time, and it was doing it so often that they started giving me Captchas!)

Do you think this should be a method on `Browser` or `Tab`, btw?

**Comment by r-darwish** [comment]
I think that one way to implement that is to allow the user to specify the Chrome data directory. If unspecified, the create will create a temporary directory like it does not. This allows to persist cookies between runs.

**Comment by atroche** [comment]
Only (potential) issue there is that you don't get fine-grained control (e.g. perhaps you only want to persist cookies for one domain, or don't want to persist localStorage). But I think it'd be a good idea to support both things.

**Comment by max-frai** [comment]
No, data directory is another story. Cookies management should be splitted and manually controlled. It's very important.
@atroche I think the method should be on browser globally. Because cookies file already contains rows only for exact domains so this will not affect wrong tabs.

**Comment by max-frai** [comment]
Hm, I looked into puppeteer, they have cookies methods on [Page](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-pagecookiesurls).

> If no URLs are specified, this method returns cookies for the current page URL. If URLs are specified, only cookies for those URLs are returned.

**Comment by atroche** [comment]
On the other hand, the protocol has "setCookies" in the Network domain: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookies

**Comment by atroche** [comment]
@max-frai `getCookies` is supported now: https://github.com/atroche/rust-headless-chrome/pull/159

**Comment by jeprojects** [comment]
@max-frai setCookies is also supported in: https://github.com/atroche/rust-headless-chrome/pull/195

**Comment by foragerDev** [comment]
Hi, I am trying to use this, to save cookies and then loading the cookies back to login automatically but so far did not get any success, can you share an example related to this?
