### ISSUE TITLE
Better default path

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#6]
https://github.com/atroche/rust-headless-chrome/blob/08050ffc4e3d37832c0e71567a4332b8c8afd165/src/process.rs#L46

As the comment says this (practically) ties everything down to MacOS and a default installation. The `Default::default()` should at least [look at](https://github.com/amodm/webbrowser-rs/blob/3158a8e4d709227320e5fb77e901136b24711d8c/src/lib.rs#L261) `$BROWSER`, which also provides default arguments.

**Comment by theduke** [comment]
I would be great to add a `feature` that downloads chrome in a `build.rs`, like puppeteer does via NPM.

**Comment by lukaslueg** [comment]
@theduke Since this is only somewhat related in intention and unrelated in implementation it'd be better to open a separate issue.

**Comment by atroche** [comment]
Definitely! This is an important one.

**Comment by r-darwish** [comment]
What I thought to do is that when the browser path is unspecified, an "autodetect" which will be involved, which looks something like this:

```rust

#[cfg(target_os = "macos")]
if (Path::from("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome").exists()) {
    // Return that path
}

#[cfg(windows)]
// Do the same for Program files

// Otherwise call which("chrome") and fall back to which("chromium")
```

**Comment by lukaslueg** [comment]
On Windows, there ~is~ could be `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe`.

**Comment by lukaslueg** [comment]
Closing this for now, since we now try to detect a default executable on all platforms
