### ISSUE TITLE
Become clippy-pedantic

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#72]
Consider adding `#![deny(clippy::all, clippy::pedantic)]` or something similar at some not so dinstant time.

There are currently a _lot_ of clippy-related warnings, most of which are of minor importance. It would be nice to wait for things to quiet down in the tree (#68, #69) and then do one big PR for all the clippy fixes.

**Comment by atroche** [comment]
Definitely!
