### ISSUE TITLE
Auto-download latest Chromium a la Puppeteer

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#8]
From https://github.com/GoogleChrome/puppeteer#installation:
> Note: When you install Puppeteer, it downloads a recent version of Chromium (~170MB Mac, ~282MB Linux, ~280MB Win) that is guaranteed to work with the API. To skip the download, see Environment variables.

See also:
https://github.com/GoogleChrome/puppeteer/blob/v1.12.2/docs/api.md#class-browserfetcher

(via @theduke in https://github.com/atroche/rust-headless-chrome/issues/6#issuecomment-463774104)

**Comment by atroche** [comment]
@leshow I think this is a particularly important issue, if you're ever in the mood. There are bound to be problems where the protocol we speak is tied to a specific Chrome / Chromium version, but our "search for the user's existing binary" set up starts using a different version.

**Comment by atroche** [comment]
@leshow (although this is a pretty big bit of work — should I try to send smaller things your way?)

**Comment by leshow** [comment]
Looks fun, I could start on it. I have a few questions though:

- Do we want to provide something like browserfetcher? 
- Or just auto download the correct version that matches the API instead of using the existing binary?
- If it's intended to be a little tool like browserfetcher, have you considered splitting the project w/ cargo workspaces? I've found them to be a great way to separate cohesive parts of a project.

**Comment by atroche** [comment]
@leshow AFAICT `BrowserFetcher` is not a standalone tool, but a part of Puppeteer's API (apologies if you already know that, just making sure we're on the same page). I'm open to making it a CLI tool, but a bit sceptical that it'd get much use (e.g. I don't have a use case for it).

For a first pass we probably don't need it to be able to handle multiple compatible Chromium versions — it could just get one (per OS) that works with the latest version of the protocol. (As far as I'm aware, by the way, we're up to date with the [tip-of-tree](https://chromedevtools.github.io/devtools-protocol/) version.)

Re. "instead of the existing binary", I say yes. Puppeteer's default behaviour is to download and use a known-to-be-matching Chromium binary unless the user specifies a path to their own binary, and I think that's a good choice.

I'm open to cargo workspaces, although it might be better to see if we can fit it in a module or two first. What problems are you anticipating?

What do you think of using `$XDG_DATA_HOME` for the location of the binaries? I found this article quite persuasive: https://0x46.net/thoughts/2019/02/01/dotfile-madness/.

**Comment by leshow** [comment]
> AFAICT `BrowserFetcher` is not a standalone tool, but a part of Puppeteer's API (apologies if you already know that, just making sure we're on the same page).

Yup, we are. 

> I'm open to cargo workspaces, although it might be better to see if we can fit it in a module or two first. What problems are you anticipating?

Just sort of throwing that out there, the cdtp and browser modules felt fairly standalone. Maybe something to think about for the future.

> What do you think of using `$XDG_DATA_HOME` for the location of the binaries?

I think that's probably the most responsible location. 

Do you have a preference for how they are downloaded? I'll probably just use reqwest if it's all the same to you.

**Comment by atroche** [comment]
Oh yeah, `cdtp` seems like a really good candidate for being separate.

No pref. re. how you do downloading :)

**Comment by leshow** [comment]
Hey, just checking in. I've done a fair amount of work on this, not quite finished yet, still need to clean some things up and refactor a bit. There's a good amount of code and one or two questions that still need to be answered, so if you don't mind I'll submit a WIP PR in the next few days.

I'm hoping we can gather some comments on the best way to land the changes and get the desired behaviour.

**Comment by atroche** [comment]
That sounds great, I'm looking forward to it.
