### ISSUE TITLE
Expand implementation of `Runtime`

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#81]
There are more objects which are highly useful in `Runtime`, including `.evaluate` and `.runScript` which we currently do not expose prominently. I've begun implementing those, including a type-safe rework of the dreaded `RemoteObject`. Announcing to prevent work duplication...

**Comment by jeprojects** [comment]
Did you end up implementing Runtime.evaluate?

**Comment by lukaslueg** [comment]
I'm afraid I lost track of this. I've pushed the [WIP](https://github.com/lukaslueg/rust-headless-chrome/commit/f97de60ae533330b2bce5b99616009e776956dcd), maybe someone wants to pick it up? It's more than 100 commits behind by now...

**Comment by atroche** [comment]
@jeprojects Not sure what your use case is, but you could probably get pretty far using [`CallFunctionOn`](https://github.com/atroche/rust-headless-chrome/blob/d5d726b089ffd6ec1661002c377b49e49a5eb0c3/tests/simple.rs#L307-L317), using "window" as your element... Of course it'd still be great to get `evaluate` at some point :)

**Comment by jeprojects** [comment]
@atroche I will take a look at evaluate using @lukaslueg as an example and use callfunction for my project at the moment.

**Comment by jeprojects** [comment]
@atroche How do I get "window" as an element?

This is what I have tried:

```
.tab
.find_element("window")?
.call_js_fn(js_code, true)?;
```

**Comment by ibaryshnikov** [comment]
@jeprojects try `wait_for_element` and "body" instead of window

**Comment by jeprojects** [comment]
@ibaryshnikov thanks for your help.

I just did pull request for Runtime.evaluate : https://github.com/atroche/rust-headless-chrome/pull/150

**Comment by skariel** [comment]
Ping. Can this be closed? The pull request is merged
