### ISSUE TITLE
Expose JS line coverage from a tab

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#82]
This is what I'll be adding to the library next, I think. I'll post a proposed API before I carry on implementing it though.

**Comment by atroche** [comment]
What do you think of this API for JS coverage tracking, @lukaslueg @leshow @r-darwish ?

References:
https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-class-coverage
https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-startPreciseCoverage

As a first pass I'm not too concerned about call counts.

```rust
#[test]
fn returns_actual_coverage() -> Result<(), Error> {
    let server = server_with_html_and_js();
    let browser = Browser::new(LaunchOptionsBuilder::default().build().unwrap()).unwrap();
    let tab: Tab = browser.wait_for_initial_tab()?;

    tab.start_js_coverage();

    let url = format!("http://127.0.0.1:{}", server.port());
    tab.navigate_to(&url)?;

    let coverage_report = tab.take_precise_js_coverage()?;
    let script_coverage = coverage_report.get_by_url(format!("{}/coverage_fixture1.js"))?;

    // see the file coverage_fixture1.js
    const ON_LOAD_LINE_NUMBER: u16 = 2;
    const  ON_CLICK_LINE_NUMBER: u16 = 7;

    let on_load_line_was_covered = script_coverage.get_line_ranges().any(|line_range| {
        line_range.contains(ON_LOAD_LINE_NUMBER);
    });
    assert!(on_load_line_was_covered);

    let on_click_line_was_not_covered = script_coverage.get_line_ranges().all(|line_range| {
        !line_range.contains(ON_CLICK_LINE_NUMBER);
    });
    assert!(on_click_line_was_not_covered);

    let button = tab.wait_for_element("#incrementor")?;
    button.click()?;

    let updated_coverage_report = tab.take_precise_js_coverage()?;
    let updated_script_coverage = coverage_report.get_by_url(format!("{}/coverage_fixture1.js"))?;

    let on_click_line_was_covered = updated_script_coverage.get_line_ranges().any(|line_range| {
        line_range.contains(ON_LOAD_LINE_NUMBER);
    });
    assert!(on_click_line_was_covered);

    let coverage_report = tab.stop_js_coverage()?;

    let coverage_report_result = tab.take_precise_js_coverage();

    // (because we stopped coverage)
    assert!(coverage_report_result.is_err());

    Ok(())
}
}
```

With that coverage fixture file looking like this:

```js
window.onload = function() {
    var a = 1;
};

var button = document.getElementById("incrementor");
button.onclick = function() {
    var b = 2;
};
```

**Comment by atroche** [comment]
Ah, one problem I can see is that I'm going by lines, but of course people will have to deal with multiple statements being on one line (e.g. in minified scripts). So I'll have to provide character or byte-level granularity.

**Comment by lukaslueg** [comment]
Two unqualified cents: I think this is fine as far as the browser interaction is concerned. I'd suggest providing a type-safe and accessible API to get the coverage reports back into Rust land but do not try to provide much magic about how to route that information back to spans / lines / characters. This is not this API's job. That is, minified scripts are not of concern here and need to be solved downstream.

I'm a little unhappy about the fact that knobs and switches like `start_js_coverage` or `Runtime.enable` have to be turned on and off manually before using the API that they cover. There could be a way to get these state-machine changes RAIIed e.g. via proxy objects but that would be even more clunky as far as I can see.

Other point: The `get_by_url(format!("{}/coverage_fixture1.js"))`-part seems just a little clunky. Maybe this is where [proper URLs](https://crates.io/crates/url) (and their constitutents) should be used?

**Comment by r-darwish** [comment]
I'm not familiar with this feature so I don't have much to say this time
