### ISSUE TITLE
Make sure all tests can pass in a CI environment

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#9]
Right now the ones testing in "headful" (aka not headless) mode might be a problem, and some of other integration tests rely in login details set in a "secrets.toml" file, which might need to be grabbed from an env var first.

**Comment by lukaslueg** [comment]
One should remove all current integration tests any use [`tiny_http`](https://crates.io/crates/tiny_http) or something similar to spin up a minimal server while testing. This would also remove the requirement of a live network connection to run those tests.

**Comment by atroche** [comment]
Good call

**Comment by atroche** [comment]
https://github.com/atroche/rust-headless-chrome/pull/57
