### ISSUE TITLE
Feature-gate the fetcher

### ISSUE THREAD

**Issue by lukaslueg** [atroche/rust-headless-chrome#93]
I was very surprised by the number of dependencies that the `fetcher`-module pulls in, including tokio, parking_lot, hyper and openssl. Especially `indicatif`,  which is far fetched for a library of this kind. This greatly increases compilation times.

As a matter of personal taste, I consider the whole progress bar thing gimmicky at best. It does, however, potentially garble `stdout/stderr` of *any* program that uses `headless_chrome` as a transient dependency.

Could we please feature-gate the whole fetcher module?

**Comment by atroche** [comment]
I think that's a good idea. Any thoughts @leshow ?

**Comment by leshow** [comment]
Sounds good to me. It would be a pretty easy change.

Also, if you really don't like the progress bar, we could always just remove that and just use log.

**Comment by leshow** [comment]
Could be a good opportunity to split off protocol as a separate module using some kind of workspace configuration also. Any thoughts on that? 

Do we want fetcher enabled or disabled by default?

**Comment by lukaslueg** [comment]
My two cents on this would be to 1) remove the progress-bar-thing entirely and 2) make the downloading-behaviour explicit instead of implicit. That is, with the feature disabled everything just works as long as Chrome is there. If the feature is enabled, one can use the fetcher module to download a working revision. `LaunchOptions` has to work the same way with/without the feature.

**Comment by leshow** [comment]
I think taking a que from puppeteer may be helpful here? By default puppeteer downloads a bundled chrome, IMO we shouldn't have a default behavior that can fail, like running system chrome that happens to be incompatible, or in an env without chrome.

Puppeteer gives you environment variables to override that behavior, we could have something like that, or put using the system chrome behind a feature like you mentioned.

**Comment by lukaslueg** [comment]
I've no strong feelings about whether or not its the default as long as the dependency chain of ~80 extra dependencies can be disabled :)

**Comment by leshow** [comment]
I can take a look at doing this sometime this week, if you like. Any other comments @atroche ?

**Comment by atroche** [comment]
I'm also okay with it being the default and being able to disable it. I think as long as it's reflected in the docs it's fine. Thanks!

**Comment by tazjin** [comment]
> IMO we shouldn't have a default behavior that can fail, like running system chrome that happens to be incompatible

Downloading a binary from the internet is also a default behaviour that can fail (if e.g. you're running a system with dynamically linked binaries in non-Debian/RedHat-conformant locations).

Regarding the number of dependencies pulled in, is that solely due to `reqwest` (the HTTP client)? In that case, there are [some](https://docs.rs/crimp/) [alternative](https://docs.rs/ureq/) clients that could be used which do not have as many dependencies (especially on `tokio`).

**Comment by leshow** [comment]
I wasn't aware of any alternatives and no others were suggested, seems fine to me to change it, I'm not married to any particular package.

I now realise I forgot to tag the PR with this issue to close, oops.
